# Generated by Django 5.1.6 on 2025-08-10 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_caregiverprofile_elderlyprofile_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('task_list', models.TextField(help_text='Comma-separated list of tasks')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elderly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.elderlyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.careschedule')),
            ],
        ),
    ]
