# Generated by Django 5.1.6 on 2025-08-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_careschedule_caregiverassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='careschedule',
            name='confirmed_by_caregiver',
            field=models.BooleanField(default=False),
        ),
    ]
