# Generated by Django 5.1.6 on 2025-08-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_careschedule_confirmed_by_caregiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careschedule',
            name='confirmed_by_caregiver',
        ),
        migrations.AddField(
            model_name='careschedule',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
