# Generated by Django 5.1.6 on 2025-08-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_careschedule_confirmed_by_caregiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careschedule',
            name='confirmed',
        ),
    ]
